name: Validate Feeds
on: [push]
jobs:
  build:
    # TODO: switch to Ubuntu, after switching Gotransit versions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    # TODO: source gotransit from its repo, rather than this hack
    - name: Try to validate feeds
      run: cd scripts && PATH=$PATH:$(pwd) python validate-feeds.py